# fly.toml app configuration file generated for wordlyze on 2023-09-13T18:23:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wordlyze"
primary_region = "sea"

[build]
  image = "docker.io/j4cob/wordlyze"

[http_service]
  internal_port = 7437
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
